figures = [
    (1,'Missingness Bar','Bar','Patient column missingness'),
    (2,'Age Histogram (dropdown)','Histogram','Age by SEX/RACE/ETHNICITY'),
    (2,'Demographics Grid','Bar+Table','Sex, race, ethnicity, age stats'),
    (3,'OS Pie','Pie','Deceased vs Living'),
    (3,'EFS Binary+Detailed Bars','Bar','EFS categories'),
    (3,'OS KM','KM','OS survival probability'),
    (3,'EFS KM','KM','EFS survival probability'),
    (4,'Predisposition Prevalence','Bar','Top 15 syndromes'),
    (4,'Predisposition Explorer','Multi','Age/sex/prevalence per syndrome'),
    (5,'Sample Missingness Bar','Bar','Missing data in samples'),
    (6,'Cancer Types Grid','Bar','Histology, group, region, type'),
    (7,'TF Histogram','Histogram','Purity distribution'),
    (7,'TP Histogram','Histogram','Ploidy distribution'),
    (7,'TF vs TP Scatter','Scatter','Purity vs ploidy by group'),
    (8,'Subtype Bar','Bar','Top 20 subtypes'),
    (8,'Subtype x Group Heatmap','Heatmap','Subtype-group cross-tab'),
    (9,'Strategy Bar','Bar','Experiment strategies'),
    (9,'Library Bar','Bar','Library prep methods'),
    ('9a','Groups per Patient','Bar','Distinct CGs per patient'),
    ('9a','Co-occurrence Heatmap','Heatmap','CG pair patterns'),
    (11,'Samples/Patient Histogram','Histogram','Samples per patient'),
    (12,'OS by CG KM','KM','OS by top 6 CGs'),
    (12,'EFS by CG KM','KM','EFS by top 6 CGs'),
    (13,'OS by Subtype KM','KM','OS by top 6 subtypes'),
    (13,'EFS by Subtype KM','KM','EFS by top 6 subtypes'),
    (13,'Subtype KM per Group','KM','Subtype survival in rich groups'),
    (14,'Age by Group Box','Box','Age distribution with KW'),
    (15,'Sex by Group Bar','Bar','Sex balance with chi2'),
    (16,'TF by Group Box','Box','Purity across groups'),
    (16,'TF by Type Box','Box','Purity by clinical state'),
    (17,'Predisposition KM','KM','OS/EFS by pred status'),
    (17,'Age by Pred Box','Box','Age by pred status'),
    (18,'CNS x CG Heatmap','Heatmap','Anatomical distribution'),
]
fd = pd.DataFrame(figures,columns=['Step','Title','Type','Insight'])
fd['Interactive'] = 'Yes'
print(f'Total figures: {len(fd)}\n')
print(fd.to_string(index=False))
