patients = read_patients()
samples = read_samples()
merged = samples.merge(patients,on='PATIENT_ID',how='left',suffixes=('','_p'))
top8 = merged['CANCER_GROUP'].value_counts().head(8).index.tolist()
pd8 = merged[merged['CANCER_GROUP'].isin(top8)].copy()
pd8['SEX'] = pd8['SEX'].fillna('Unknown')
ct = pd.crosstab(pd8['CANCER_GROUP'],pd8['SEX'])
fig = go.Figure()
for sex in ct.columns:
    fig.add_trace(go.Bar(name=sex,x=ct.index,y=ct[sex],text=ct[sex],textposition='inside'))
chi2,p,_,_ = chi2_contingency(ct)
fig.add_annotation(xref='paper',yref='paper',x=0.5,y=1.05,text=f'Chi2: x2={chi2:.2f}, p={p:.4f}',showarrow=False,font=dict(size=12,color='darkred'))
fig.update_layout(barmode='stack',title='Sex by Cancer Group',xaxis_tickangle=-45,height=450)
fig.show()
