fig2 = make_subplots(rows=2,cols=2,subplot_titles=('Sex','Race','Ethnicity','Age Stats'),specs=[[{'type':'bar'},{'type':'bar'}],[{'type':'bar'},{'type':'table'}]])
sc = df['SEX'].fillna('NaN').value_counts()
fig2.add_trace(go.Bar(x=sc.index,y=sc.values,marker_color='lightblue',text=sc.values,textposition='outside',showlegend=False),row=1,col=1)
rc = df['RACE'].value_counts()
fig2.add_trace(go.Bar(x=rc.index,y=rc.values,marker_color='lightgreen',text=rc.values,textposition='outside',showlegend=False),row=1,col=2)
ec = df['ETHNICITY'].value_counts()
fig2.add_trace(go.Bar(x=ec.index,y=ec.values,marker_color='lightskyblue',text=ec.values,textposition='outside',showlegend=False),row=2,col=1)
ac = df['AGE'].dropna()
tbl = pd.DataFrame([['Count',str(len(ac))],['Mean',f'{ac.mean():.1f}'],['Median',f'{ac.median():.1f}'],['Min',f'{ac.min():.1f}'],['Max',f'{ac.max():.1f}'],['Missing',str(df['AGE'].isna().sum())]],columns=['Stat','Value'])
fig2.add_trace(go.Table(header=dict(values=['Stat','Value'],fill_color='lightblue',align='left'),cells=dict(values=[tbl['Stat'],tbl['Value']],align='left',height=25)),row=2,col=2)
fig2.update_layout(height=600,title='Patient Demographics')
fig2.show()
