patients = read_patients()
samples = read_samples()
merged = samples.merge(patients,on='PATIENT_ID',how='left',suffixes=('','_p'))
print(f'Merged: {merged.shape}')
print(f'Samples: {len(samples)}, Patients: {len(patients)}')
sp = set(samples['PATIENT_ID'].unique())
pp = set(patients['PATIENT_ID'].unique())
print(f'Orphan samples: {len(sp-pp)}')
print(f'Orphan patients: {len(pp-sp)}')
