fig = make_subplots(rows=2,cols=1,subplot_titles=('OS -- KM','EFS -- KM'),vertical_spacing=0.15)
os_c = df[['OS_MONTHS','os_event']].dropna()
fig = add_km(fig, kaplan_meier(os_c['OS_MONTHS'],os_c['os_event']), 'OS', 'darkblue')
efs_c = df[['EFS_MONTHS','efs_event']].dropna()
km = kaplan_meier(efs_c['EFS_MONTHS'],efs_c['efs_event'])
fig.add_trace(go.Scatter(x=km['t'],y=km['s'],mode='lines',name='EFS',line=dict(color='darkred',width=2,shape='hv')),row=2,col=1)
fig.update_layout(height=600,title='KM Survival Curves')
fig.update_yaxes(range=[-0.05,1.05])
fig.show()
